import {PlayersModel} from "./players.model";

export const PlayersData: PlayersModel[] = [
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Kobe Bryant', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Kobe Bryant', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Kobe Bryant', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Nikola Mirotić', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'},
  {name: 'Kobe Bryant', team: 'EA7 EAM', position: 'F', height: 208, nationality: 'Spain'}
]
