import {TeamModel} from "./team.model";

export const TeamsBCL: TeamModel[] = [
  {name: 'AEK BETSSON BC', logo: 'assets/img/logos/bcl/AEK-BETSSON-BC.png'},
  {name: 'Banco di Sardegna Sassari', logo: 'assets/img/logos/bcl/Banco-di-Sardegna-Sassari.png'},
  {name: 'Bertram Derthona Tortona', logo: 'assets/img/logos/bcl/Bertram-Derthona-Tortona.png'},
  {name: 'BK Opava', logo: 'assets/img/logos/bcl/BK-Opava.png'},
  {name: 'Bursaspor Info Yatirim', logo: 'assets/img/logos/bcl/Bursaspor-Info-Yatirim.png'},
  {name: 'Cholet Basket', logo: 'assets/img/logos/bcl/Cholet-Basket.png'},
  {name: 'Darüssafaka Lassa', logo: 'assets/img/logos/bcl/Darüssafaka-Lassa.png'},
  {name: 'EWE Baskets Oldenburg', logo: 'assets/img/logos/bcl/EWE-Baskets-Oldenburg.png'},
  {name: 'Falco Vulcano Szombathely', logo: 'assets/img/logos/bcl/Falco-Vulcano-Szombathely.png'},
  {name: 'Filou Oostende', logo: 'assets/img/logos/bcl/Filou-Oostende.png'},
  {name: 'Galatasaray EKMAS', logo: 'assets/img/logos/bcl/Galatasaray-EKMAS.png'},
  {name: 'Hapoel Bank Yahav Jerusalem', logo: 'assets/img/logos/bcl/Hapoel-Bank-Yahav-Jerusalem.png'},
  {name: 'Hapoel Holon', logo: 'assets/img/logos/bcl/Hapoel-Holon.png'},
  {name: 'Igokea m:tel', logo: 'assets/img/logos/bcl/Igokea-mtel.png'},
  {name: 'JDA Bourgogne Dijon', logo: 'assets/img/logos/bcl/JDA-Bourgogne-Dijon.png'},
  {name: 'King Szczecin', logo: 'assets/img/logos/bcl/King-Szczecin.png'},
  {name: 'Le Mans Sarthe Basket', logo: 'assets/img/logos/bcl/Le-Mans-Sarthe-Basket.png'},
  {name: 'Lenovo Tenerife', logo: 'assets/img/logos/bcl/Lenovo-Tenerife.png'},
  {name: 'MHP RIESEN Ludwigsburg', logo: 'assets/img/logos/bcl/MHP-RIESEN-Ludwigsburg.png'},
  {name: 'PAOK mateco', logo: 'assets/img/logos/bcl/PAOK-mateco.png'},
  {name: 'Peristeri bwin', logo: 'assets/img/logos/bcl/Peristeri-bwin.png'},
  {name: 'Pinar Karsiyaka', logo: 'assets/img/logos/bcl/Pinar-Karsiyaka.png'},
  {name: 'Promitheas Patras', logo: 'assets/img/logos/bcl/Promitheas-Patras.png'},
  {name: 'Rio Breogan', logo: 'assets/img/logos/bcl/Rio-Breogan.png'},
  {name: 'Rytas Vilnius', logo: 'assets/img/logos/bcl/Rytas-Vilnius.png'},
  {name: 'SIG Strasbourg', logo: 'assets/img/logos/bcl/SIG-Strasbourg.png'},
  {name: 'SL Benfica', logo: 'assets/img/logos/bcl/SL-Benfica.png'},
  {name: 'Telekom Baskets Bonn', logo: 'assets/img/logos/bcl/Telekom-Baskets-Bonn.png'},
  {name: 'Tofas Bursa', logo: 'assets/img/logos/bcl/Tofas-Bursa.png'},
  {name: 'UCAM Murcia', logo: 'assets/img/logos/bcl/UCAM-Murcia.png'},
  {name: 'Unicaja', logo: 'assets/img/logos/bcl/Unicaja.png'},
  {name: 'VEF Riga', logo: 'assets/img/logos/bcl/VEF-Riga.png'}
];
